name: Shell Script Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
	uses: actions/checkout@v4

　　　- name: Permission Setting
　　　　run: chmod +x GCD_Calculation.sh GCD_Calculation_Test.sh

      - name: テストスクリプトを実行
        run: ./GCD_Calculation_Test.sh
